### ISSUE TITLE
On the bugs page, clicking 'Return to the home page' shows an error

### ISSUE THREAD

**Issue by Mippy** [ItsPugle/DiscordApp#20]
Steps to Reproduce:
Go to https://howtodiscord.tk/
Click 'Bugs'
Click '< Return to the home page'

**Comment by ItsPugle** [comment]
I'll look into it now! In the meantime:
![Sorry!](https://media.giphy.com/media/13CoXDiaCcCoyk/giphy.gif)

**Comment by ItsPugle** [comment]
I just pushed a change (9959ec8) that should fix this.

**Comment by advaith1** [comment]
oh yeah, thats because that link was made before howtodiscord.tk was set up, and the link structure was /DiscordApp/filename

**Comment by advaith1** [comment]
confirmed fixed
