### ISSUE TITLE
Should I create a folder for Bug Hunter related docs, or a single file?

### ISSUE THREAD

**Issue by ItsPugle** [ItsPugle/DiscordApp#3]
Should I create a folder under docs/bugs called bug hunters, or should I create a bughunters.md file? It'd contain stuff like:

- Appropriate approve/deny messages
- Bug Hunter only commands
- Tips and tricks

Stuff like that, that might help new Bug Hunters, and refresh the experienced.

**Comment by Tim-The** [comment]
I think a folder is the beter for the future when we would add more info regarding bug hunters
